spring:
  datasource:
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false;
    driverClassName: org.h2.Driver
    username: nana
    password: nanana
  h2.console.enabled: true
  sql:
    init:
      mode: always
server:
  port: 8081    

  
